export const ERROR = 'ERROR';
export const SET_LAST_PODCAST_LIST = 'SET_LAST_PODCAST_LIST';
export const SET_LOADING = 'SET_LOADING';
export const SET_PODCAST_LIST_FILTERED = 'SET_PODCAST_LIST_FILTERED';
export const SET_PODCAST_LOADED = 'SET_PODCAST_LOADED';
